// This file is automatically generated by qtc from "app.json.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line app.json.qtpl:1
package templates

//line app.json.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line app.json.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line app.json.qtpl:1
func StreamAppJsonTemplate(qw422016 *qt422016.Writer, projectSlug string) {
	//line app.json.qtpl:1
	qw422016.N().S(`{
    "name": "",
    "description": "",
    "keywords": [],
    "website": "",
    "repository": "https://github.com/.../`)
	//line app.json.qtpl:6
	qw422016.E().S(projectSlug)
	//line app.json.qtpl:6
	qw422016.N().S(`",
    "formation": {
        "web": {
            "quantity": 1,
            "size": "Free"
        }
    }
}`)
//line app.json.qtpl:13
}

//line app.json.qtpl:13
func WriteAppJsonTemplate(qq422016 qtio422016.Writer, projectSlug string) {
	//line app.json.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line app.json.qtpl:13
	StreamAppJsonTemplate(qw422016, projectSlug)
	//line app.json.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line app.json.qtpl:13
}

//line app.json.qtpl:13
func AppJsonTemplate(projectSlug string) string {
	//line app.json.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
	//line app.json.qtpl:13
	WriteAppJsonTemplate(qb422016, projectSlug)
	//line app.json.qtpl:13
	qs422016 := string(qb422016.B)
	//line app.json.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
	//line app.json.qtpl:13
	return qs422016
//line app.json.qtpl:13
}
