// This file is automatically generated by qtc from "dotenv.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line dotenv.qtpl:1
package templates

//line dotenv.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line dotenv.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line dotenv.qtpl:1
func StreamDotEnvTemplate(qw422016 *qt422016.Writer, projectSlug string) {
//line dotenv.qtpl:1
qw422016.N().S(`REPEAT=10`) }

//line dotenv.qtpl:1
//line dotenv.qtpl:1
func WriteDotEnvTemplate(qq422016 qtio422016.Writer, projectSlug string) {
	//line dotenv.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line dotenv.qtpl:1
	StreamDotEnvTemplate(qw422016, projectSlug)
	//line dotenv.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line dotenv.qtpl:1
}

//line dotenv.qtpl:1
func DotEnvTemplate(projectSlug string) string {
	//line dotenv.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
	//line dotenv.qtpl:1
	WriteDotEnvTemplate(qb422016, projectSlug)
	//line dotenv.qtpl:1
	qs422016 := string(qb422016.B)
	//line dotenv.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
	//line dotenv.qtpl:1
	return qs422016
//line dotenv.qtpl:1
}
