// This file is automatically generated by qtc from "heroku.yml.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line heroku.yml.qtpl:1
package templates

//line heroku.yml.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line heroku.yml.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line heroku.yml.qtpl:1
func StreamHerokuYmlTemplate(qw422016 *qt422016.Writer, projectSlug string) {
	//line heroku.yml.qtpl:1
	qw422016.N().S(`# https://devcenter.heroku.com/articles/heroku-yml-build-manifest
# Officially unsupported, but works.
build:
  languages:
    - go

run:
  web: `)
	//line heroku.yml.qtpl:8
	qw422016.E().S(projectSlug)
//line heroku.yml.qtpl:8
}

//line heroku.yml.qtpl:8
func WriteHerokuYmlTemplate(qq422016 qtio422016.Writer, projectSlug string) {
	//line heroku.yml.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line heroku.yml.qtpl:8
	StreamHerokuYmlTemplate(qw422016, projectSlug)
	//line heroku.yml.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line heroku.yml.qtpl:8
}

//line heroku.yml.qtpl:8
func HerokuYmlTemplate(projectSlug string) string {
	//line heroku.yml.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
	//line heroku.yml.qtpl:8
	WriteHerokuYmlTemplate(qb422016, projectSlug)
	//line heroku.yml.qtpl:8
	qs422016 := string(qb422016.B)
	//line heroku.yml.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
	//line heroku.yml.qtpl:8
	return qs422016
//line heroku.yml.qtpl:8
}
