// This file is automatically generated by qtc from "Makefile.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line Makefile.qtpl:1
package templates

//line Makefile.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line Makefile.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line Makefile.qtpl:1
func StreamMakefileTemplate(qw422016 *qt422016.Writer, projectSlug string) {
	//line Makefile.qtpl:1
	qw422016.N().S(`GO_BUILD_ENV := CGO_ENABLED=0 GOOS=linux GOARCH=amd64
DOCKER_BUILD=$(shell pwd)/.docker_build
DOCKER_CMD=$(DOCKER_BUILD)/`)
	//line Makefile.qtpl:3
	qw422016.E().S(projectSlug)
	//line Makefile.qtpl:3
	qw422016.N().S(`

$(DOCKER_CMD): clean
	mkdir -p $(DOCKER_BUILD)
	$(GO_BUILD_ENV) go build -v -o $(DOCKER_CMD) .

clean:
	rm -rf $(DOCKER_BUILD)

heroku: $(DOCKER_CMD)
	heroku container:push web`)
//line Makefile.qtpl:13
}

//line Makefile.qtpl:13
func WriteMakefileTemplate(qq422016 qtio422016.Writer, projectSlug string) {
	//line Makefile.qtpl:13
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line Makefile.qtpl:13
	StreamMakefileTemplate(qw422016, projectSlug)
	//line Makefile.qtpl:13
	qt422016.ReleaseWriter(qw422016)
//line Makefile.qtpl:13
}

//line Makefile.qtpl:13
func MakefileTemplate(projectSlug string) string {
	//line Makefile.qtpl:13
	qb422016 := qt422016.AcquireByteBuffer()
	//line Makefile.qtpl:13
	WriteMakefileTemplate(qb422016, projectSlug)
	//line Makefile.qtpl:13
	qs422016 := string(qb422016.B)
	//line Makefile.qtpl:13
	qt422016.ReleaseByteBuffer(qb422016)
	//line Makefile.qtpl:13
	return qs422016
//line Makefile.qtpl:13
}
