// This file is automatically generated by qtc from "Procfile.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line Procfile.qtpl:1
package templates

//line Procfile.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line Procfile.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line Procfile.qtpl:1
func StreamProcfileTemplate(qw422016 *qt422016.Writer, projectSlug string) {
	//line Procfile.qtpl:1
	qw422016.N().S(`web: `)
	//line Procfile.qtpl:1
	qw422016.E().S(projectSlug)
//line Procfile.qtpl:1
}

//line Procfile.qtpl:1
func WriteProcfileTemplate(qq422016 qtio422016.Writer, projectSlug string) {
	//line Procfile.qtpl:1
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line Procfile.qtpl:1
	StreamProcfileTemplate(qw422016, projectSlug)
	//line Procfile.qtpl:1
	qt422016.ReleaseWriter(qw422016)
//line Procfile.qtpl:1
}

//line Procfile.qtpl:1
func ProcfileTemplate(projectSlug string) string {
	//line Procfile.qtpl:1
	qb422016 := qt422016.AcquireByteBuffer()
	//line Procfile.qtpl:1
	WriteProcfileTemplate(qb422016, projectSlug)
	//line Procfile.qtpl:1
	qs422016 := string(qb422016.B)
	//line Procfile.qtpl:1
	qt422016.ReleaseByteBuffer(qb422016)
	//line Procfile.qtpl:1
	return qs422016
//line Procfile.qtpl:1
}
